### ISSUE TITLE
NEWBORN BLOOD SPOT TEST OUTCOME STATUS

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#320]
See V3: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/n/ne/newborn_blood_spot_test_outcome_status_de.asp?shownav=1
The item is NEWBORN BLOOD SPOT TEST OUTCOME STATUS with a formerly name of "NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE".

See V3+: https://www.datadictionary.nhs.uk/attributes/newborn_blood_spot_test_outcome_status_code.html
The item name is NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE.

V3+ needs correcting.
Is this an issue with Mauro or the files produced by Likin?
I hope there aren't any more like this.

**Comment by maxChappell** [comment]
Ontoserver content is correct (Name etc. omits code suffix). Need to check the knitted files next - awaiting Likin return, as I don't have access to the knitted files.

**Comment by maxChappell** [comment]
Likin is doing detailed investigation - there are 2 name properties listed for this item in the knitted file.

**Comment by jamesrwelch** [comment]
There are 10 items in the XML that have multiple values for 'name'.  In some examples, both entries are the same.  The complete list is:

**Comment by AngelaFaulding** [comment]
- ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE
Attribute and Data Element OK in both: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/a/ar/asa_physical_status_classification_system_code_de.asp?shownav=1 and https://www.datadictionary.nhs.uk/attributes/asa_physical_status_classification_system_code.html

- CARE_PROFESSIONAL_TEAM_IDENTIFIER
Attribute OK in both: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/c/card/care_professional_team_identifier_de.asp?shownav=1 and https://www.datadictionary.nhs.uk/attributes/care_professional_team_identifier.html
**Data Elements not the same:
V3 has: https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/c/care/care_professional_team_local_identifier_de.asp?shownav=1
V3+ has: https://www.datadictionary.nhs.uk/data_elements/care_professional_team_identifier.html**

- ADULT_MENTAL_HEALTH_CARE_TEAM_TYPE
V3: ADULT MENTAL HEALTH CARE TEAM TYPE Attribute and Data Element retired.
V3+: ADULT MENTAL HEALTH CARE TEAM TYPE Attribute and Data Element retired.

- DATA_SET_SEGMENT_IDENTIFIER_(CHILDREN_AND_YOUNG_PEOPLES_HEALTH_SERVICES_SECONDARY_USES_DATA_SET)
V3: DATA SET SEGMENT IDENTIFIER (CHILDREN AND YOUNG PEOPLES HEALTH SERVICES SECONDARY USES DATA SET Data Element retired.
V3+: DATA SET SEGMENT IDENTIFIER (CHILDREN AND YOUNG PEOPLES HEALTH SERVICES SECONDARY USES DATA SET) Data Element retired.

- HEALTH_PROGRAMME_STAGE_NUMBER (HUMAN_PAPILLOMAVIRUS_VACCINE)
V3: HEALTH PROGRAMME STAGE NUMBER (HUMAN PAPILLOMAVIRUS VACCINE) Data Element retired.
V3+: HEALTH PROGRAMME STAGE NUMBER (HUMAN PAPILLOMAVIRUS VACCINE) Data Element retired

- SITE_CODE_(OF_PROVIDER_FIRST_SEEN)
V3: SITE CODE (OF PROVIDER FIRST SEEN) Data Element retired.
V3+: SITE CODE (OF PROVIDER FIRST SEEN) Data Element retired.

- Central_Returns_Introduction
Central Returns Introduction not present in V3 or V3+. 
Central Return Forms Introduction retired in V3.
Nothing similar in V3+.

- Cancer_Outcomes_and_Services_Data_Set_Submission_Requirements
Cancer Outcomes and Services Data Set Submission Requirements retired in V3.
Cancer Outcomes and Services Data Set Submission Requirements not present in V3+

- Commissioning_Data_Set_Version_6-2_Type_List
V3: Commissioning Data Set Version CDS 6-2 Type List
Commissioning Data Set Version CDS 6-2 Type List not present in V3+

**Comment by AngelaFaulding** [comment]
These are another few that Likin has passed to me by email:

- /Data_Dictionary/Classes/O/OPHTHALMIC_MEDICAL_PRACTITIONER.txaClass20
Look OK in both

- /Data_Dictionary/Messages/Message_Documentation/Data_Set_Constraints/PLICS_Integrated_Data_Set_Out-Patient_Care_(Acute)_Constraints.txaClass20
Look OK in both

- /Data_Dictionary/Messages/Message_Documentation/Data_Set_Constraints/PLICS_Integrated_Data_Set_Emergency_Care_(Acute)_Constraints.txaClass20
Look OK in both

- /Data_Dictionary/Messages/Message_Documentation/Data_Set_Constraints/PLICS_Integrated_Data_Set_Improving_Access_to_Psychological_Therapies_Constraints.txaClass20
Looks OK in V3+.
Can't find it in V3.

- /Data_Dictionary/Messages/Message_Documentation/Data_Set_Constraints/PLICS_Integrated_Data_Set_Admitted_Patient_Care_(Acute)_Constraints.txaClass20
Look OK in both

- /Data_Dictionary/Messages/Message_Documentation/Data_Set_Constraints/PLICS_Integrated_Data_Set_Specialist_Ward_Care_(Acute)_Constraints.txaClass20
Look OK in both

- /Data_Dictionary/Messages/Message_Documentation/Data_Set_Constraints/PLICS_Integrated_Data_Set_Mental_Health_Admitted_Patient_Care_Constraints.txaClass20
Look OK in both

The All Items Index in V3+ for the PLICS Constraints pages looks odd:
![image](https://user-images.githubusercontent.com/62995711/150120371-f30d81d3-0255-4620-9561-1fa8a3b37634.png)

They also look odd on the Supporting Information menu:
![image](https://user-images.githubusercontent.com/62995711/150121675-376abe2a-aa8e-43e5-b9a9-2fc9c4c2b014.png)
- /Retired/Data_Dictionary/Messages/Message_Documentation/Maternity_and_Childrens_Data_Sets_Submission_Requirements.txaClass20
Retired in V3.
Not present in V3+.

**Comment by AngelaFaulding** [comment]
To clarify V3+ needs correcting for 2 items:

- NEWBORN BLOOD SPOT TEST OUTCOME STATUS
See V3: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/n/ne/newborn_blood_spot_test_outcome_status_de.asp?shownav=1
The item is NEWBORN BLOOD SPOT TEST OUTCOME STATUS with a formerly name of "NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE".
See V3+: https://www.datadictionary.nhs.uk/attributes/newborn_blood_spot_test_outcome_status_code.html
The item name is NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE.

- CARE_PROFESSIONAL_TEAM_IDENTIFIER

Attribute OK in both: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/c/card/care_professional_team_identifier_de.asp?shownav=1 and https://www.datadictionary.nhs.uk/attributes/care_professional_team_identifier.html
Data Elements not the same:
V3 has: https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/c/care/care_professional_team_local_identifier_de.asp?shownav=1
V3+ has: https://www.datadictionary.nhs.uk/data_elements/care_professional_team_identifier.html

**Comment by AngelaFaulding** [comment]
James need to check if this has been fixed.

**Comment by AngelaFaulding** [comment]
15/2/22 - once James has fixed this we will have to check the DITA output.

**Comment by PaulChapmanPM** [comment]
James believes this is fixed in the Mauro pipeline but not in the current Metadata pipeline that is publishing the latest releases.
James to confirm.

**Comment by AngelaFaulding** [comment]
I have checked the test publish for March 2022 and the 2 items below are still incorrect:

- NEWBORN BLOOD SPOT TEST OUTCOME STATUS

See V3: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/n/ne/newborn_blood_spot_test_outcome_status_de.asp?shownav=1
The item is NEWBORN BLOOD SPOT TEST OUTCOME STATUS with a formerly name of "NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE".
See V3+: https://dduat.dev.dataproducts.nhs.uk/attributes/newborn_blood_spot_test_outcome_status_code.html
The item name is NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE.

- CARE PROFESSIONAL TEAM IDENTIFIER

Attribute OK in both: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/c/card/care_professional_team_identifier_de.asp?shownav=1 and https://dduat.dev.dataproducts.nhs.uk/attributes/care_professional_identifier.html#attribute_care_professional_identifier.where_used
Data Elements not the same:
V3 has: https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/c/care/care_professional_team_local_identifier_de.asp?shownav=1
V3+ has: https://dduat.dev.dataproducts.nhs.uk/data_elements/care_professional_local_identifier.html

**Comment by AngelaFaulding** [comment]
March release published and the items are still incorrect:
https://www.datadictionary.nhs.uk/attributes/newborn_blood_spot_test_outcome_status_code.html
https://dduat.dev.dataproducts.nhs.uk/data_elements/care_professional_local_identifier.html

**Comment by AngelaFaulding** [comment]
This has been fixed. https://www.datadictionary.nhs.uk/attributes/newborn_blood_spot_test_outcome_status_code.html has "Page last Published - 25/11/2021".
Also, https://www.datadictionary.nhs.uk/data_elements/care_professional_team_identifier.html has "Page last Published - 25/11/2021".
Needs to be checked in the next release. 
Also, need to ensure that old content is removed from the website.

**Comment by AngelaFaulding** [comment]
Correct in the April release so issue closed.
