### ISSUE TITLE
Childhood Immunisation Type issues

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#43]
CHILDHOOD_IMMUNISATION_TYPE:
- CHILDHOOD_IMMUNISATION_TYPE is the list https://modelcatalogue.cs.ox.ac.uk/datadictionary/attributes/c/c.html but not in https://modelcatalogue.cs.ox.ac.uk/datadictionary/attributes/c/ce.html
- CHILDHOOD_IMMUNISATION_TYPE isn’t correct.

**Comment by maxChappell** [comment]
Looks like this is now fixed?

**Comment by AngelaFaulding** [comment]
This isn't fixed, beta (ce section) has:
CHILD PUGH SCORE
CHILDHOOD IMMUNISATION TYPE COMBINED
CHILDREN TEENAGERS AND YOUNG ADULTS AGE CATEGORY

The current version has:
CHILD DIFFICULT TO TEST REASON
CHILDHOOD IMMUNISATION TYPE
CHILDHOOD IMMUNISATION TYPE COMBINED
CHILD PROTECTION PLAN INDICATION CODE

CHILDHOOD IMMUNISATION TYPE is still missing.
