### ISSUE TITLE
Preparatory item not displaying correctly in the Orchestrator

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#539]
Preparatory items are not displaying correctly in the Orchestrator.
The short description should not be there.

Is this linked to #459?

![image](https://github.com/user-attachments/assets/d0421b8f-f776-431b-a674-55125755bcc5)

**Comment by pjmonks** [comment]
Apart from the unusual formatting of `<p>` tags, since a short description is set on these items then that is why they are appearing. System C were not informed about any different requirements for this, so we consider this out of scope - except for fixing the HTML formatting in the short description.

**Comment by AngelaFaulding** [comment]
The SOW needs updating to show that this hasn't been delivered.
A preparatory item is hidden from the dictionary until it is approved. Therefore the short description should not display the text.

**Comment by AngelaFaulding** [comment]
Peter thinks this may now be fixed so will check.

**Comment by pjmonks** [comment]
This issue has been fixed and deployed to TEST, TRAINING and LIVE. Please move this to the "Ready for NHS E Testing" state.

**Comment by pjmonks** [comment]
To test, change an item's status between preparatory and not-preparatory, then check the preview of the item. I usually open two tabs for the same item - one in Mauro, one in Orchestrator preview - then make changes in one and refresh the preview in the other.

**Comment by AngelaFaulding** [comment]
I have made the NHS Business Definition Eye Colour preparatory in a new CR8009 and the short description is still not showing correctly.

![image](https://github.com/user-attachments/assets/c435a5c0-acec-4c82-8f4f-b16b17149bb1)

I also made the Data Element EYE COLOUR IDENTIFIER preparatory in CR8000 and the short description is still not showing correctly. This also linked to #554.

![image](https://github.com/user-attachments/assets/d83bdeb4-4328-4231-99ee-f7c371b17927)

**Comment by AngelaFaulding** [comment]
If this is the same as the preview via the DDPM, this will prevent migration.

**Comment by pjmonks** [comment]
Please clarify what should happen so I am clear - if an item is preparatory, what should it look like? What sections should appear or not appear? Please provide a link or screenshot as well to an example, I might find that useful.

**Comment by AngelaFaulding** [comment]
30/09/24 - for the Orchestrator and live dictionary, Peter is going to add the short description, description and change log on all prep items.
Everything else will be removed.

**Comment by pjmonks** [comment]
It was agreed in the meeting on 30/09/2024 that preparatory item pages will contain:

* Short description
* Preparatory text template (instead of the item description)
* Change log (New)

They will _not_ include:

* Original description
* Format/Length (for Elements)
* National Codes (for Elements/Attributes)
* Default Codes (for Elements)
* Attributes (for Classes)
* Relationships (for Classes)
* Linked Attributes (for Elements)
* Linked Elements (for Attributes)
* Aliases
* Specifications (for Data Sets)

If an item is preparatory, it may appear as a link on another page.

**Comment by pjmonks** [comment]
I have deployed to TEST the changes described in my last comment.

**Comment by AngelaFaulding** [comment]
Prep items are now showing correctly in the Orchestrator:

![image](https://github.com/user-attachments/assets/9f5c34bb-bfb2-41f9-a20e-1580f3cdb545)
