### ISSUE TITLE
How to retire a Data Set

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#551]
I am trying to retire the Central Return Data Set: NHS Continuing Healthcare Data Set in the Test branch.

I have selected the retired tick box in the profile:

![image](https://github.com/user-attachments/assets/5e57dbc7-06a9-49f9-bc86-f8afbf50bfab)

I have looked in the Orchestrator and the data set is showing as retired but the data set overview and data set is displayed:

![image](https://github.com/user-attachments/assets/b0f0a552-59c1-4fce-835d-ad3243a3b5c5)

What do I need to do to add the retired text to the data set page?

**Comment by pjmonks** [comment]
What is the "retired text"? We have one issue logged related to retired items:

- MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#36

But it there is different text to display, just edit the description of the item in question - in this case the description of the data set.

Apart from the listed issue above, anything else feels like it is out of scope and should be discussed with @jamesrwelch

**Comment by AngelaFaulding** [comment]
Sorry @pjmonks, I am a little confused by this.
The SOW shows that all items can be retired but data sets obviously can't. The SOW will need to be updated to reflect this.
Should we be have to retire each data group and sub group separately? There is no option in the profile to do this.

An example of a date set that was live and is now retired is shown below. This what we expect we retire a data set:

https://archive.datadictionary.nhs.uk/DD%20Release%20November%202023/data_sets/supporting_data_sets/plics_data_set/patient_level_information_costing_system_ambulance_data_set.html

https://www.datadictionary.nhs.uk/data_sets/retired/supporting_data_sets/patient_level_information_costing_system_ambulance_data_set.html

**Comment by AngelaFaulding** [comment]
Peter will investigate.

**Comment by pjmonks** [comment]
This issue has been fixed and deployed to TEST, TRAINING and LIVE. Please move this to the "Ready for NHS E Testing" state.

**Comment by pjmonks** [comment]
The fix was that any data set marked as retired now shows the "retired" description and hides the specification tables.

**Comment by AngelaFaulding** [comment]
@pjmonks - this works better for the Orchestrator: 
![image](https://github.com/user-attachments/assets/a214f0ff-e4b0-4a5e-8dc5-1511f5fb7191)

Mauro still shows the data groups and sub groups and they are not marked as retired. Is that what you intended?

![image](https://github.com/user-attachments/assets/0a38eba2-b2fe-4e98-b35f-d04edfb9009b)

**Comment by AngelaFaulding** [comment]
I have run a CR preview and all the Data Elements in the data set appear to be included in the data set which isn't correct.
[CR8008_retire a data set.docx](https://github.com/user-attachments/files/17014965/CR8008_retire.a.data.set.docx)
@pjmonks  - could you please investigate?

**Comment by pjmonks** [comment]
You are correct, retired/preparatory data sets should not be listing their Elements/Attributes in the summary of changes. I have created this issue to fix for the next release:

- MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#123

**Comment by AngelaFaulding** [comment]
Ticket moved as Peter is looking into this.

**Comment by pjmonks** [comment]
A fix has just been deployed to TEST. Now, when you generate a change paper (or a preview) and it includes a data set that has been retired:

1. The data set change will be listed. The retired description text will appear showing the change.
2. Any Attributes and Data Elements linked to that particular data set will not appear in the Summary of Changes list as "Changed Data Set"

**Comment by AngelaFaulding** [comment]
@pjmonks - the changes now don't include the Data Elements from the retired data set, thanks.

Can you please answer my questions from above (copied below).

- Mauro still shows the data groups and sub groups and they are not marked as retired. Is that what you intended? There is no option to retire them.
- Will the groups appear if you searched the dictionary?
- What would happen if we deleted the data groups and sub groups so they look like other retired data sets?
- How do we make the data set look like the other retired data sets?

![image](https://github.com/user-attachments/assets/c3306ce6-a6b3-4773-962c-bc6b0862590b)

**Comment by jamesrwelch** [comment]
I haven't seen what Pete has implemented, but the intention is:
- You don't need to mark all the groups of a data set as retired if you want to retire a dataset.  I've not seen a use case yet for marking data groups in a data set as retired.
- No, there are no separate pages for data groups in the dictionary, and the retired data set pages should not show the data set structure
- You shouldn't delete the structure, simply marking the dataset as retired is sufficient.  The structures for the previously retired data sets has never appeared in the ingest XML that comes out of Borland, and since we've never put it on the web pages, I've never asked for it.  But ideally we would keep retired content, just as we do for all other items.

**Comment by jamesrwelch** [comment]
This also applies for retiring attributes and data elements - you should not need to retire the codes individually.  Equally you should not need to retire all the attributes when you retire a class.

**Comment by pjmonks** [comment]
I apologise for not answering your earlier question - a lot of these issues have a long history to them, some dating back years, so I struggle to keep up to date with the latest state of them.

All of what @jamesrwelch has said I agree with, to retire a data set my understanding is you only retire the data set itself and everything below it (tables/groups/rows) are also considered "retired". If you delete retired items then you will lose valuable information from your model, which I don't believe you want to do.

**Comment by AngelaFaulding** [comment]
@pjmonks and @jamesrwelch - Will the groups appear if you searched the dictionary?
Also, are you saying, it doesn't matter that newly retired data sets won't look like the other retired data sets?

**Comment by jamesrwelch** [comment]
If you search the generated website?  No, because it only indexes the content of the pages, and there will be no pages showing the groups.  
I would expect them to look, from the generated pages, exactly the same as the previously retired data sets.  In Mauro, however, they will look a bit different because we don't have the structure for the datasets that have been retired in Together, but we do in Mauro.  If the structure of retired data sets still exists in Together, then we could get Likin to modify the extract code so that they appear in the XML, and then we can have it all in Mauro.
